### ISSUE TITLE
[macOS] Build failure since DX10 was enabled upstream

### ISSUE THREAD

**Issue by Luke-Nukem** [ValveSoftware/dxvk#2]
This is an issue with changing the rpath using native macOS tooling:

```
Stripping target 'src/d3d10/d3d10core.dll'
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin/meson", line 29, in <module>
    sys.exit(mesonmain.main())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 379, in main
    return run(sys.argv[1:], launcher)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 284, in run
    return minstall.run(remaining_args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mesonbuild/minstall.py", line 466, in run
    installer.do_install(datafilename)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mesonbuild/minstall.py", line 298, in do_install
    self.install_targets(d)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mesonbuild/minstall.py", line 442, in install_targets
    install_name_mappings, verbose=False)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mesonbuild/scripts/depfixer.py", line 412, in fix_rpath
    fix_darwin(fname, new_rpath, final_path, install_name_mappings)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mesonbuild/scripts/depfixer.py", line 394, in fix_darwin
    stderr=subprocess.DEVNULL)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['install_name_tool', '/Users/luke/src/Proton/build/dxvk.win32/bin/d3d10core.dll', '-change', '@rpath/d3d11.dylib', '/Users/luke/src/Proton/build/dxvk.win32/bin/d3d11.dll']' returned non-zero exit status 1.
FAILED: meson-install 
/opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

Issue originally reported [here](https://github.com/doitsujin/dxvk/issues/601).

There is also no linking of MoltenVK to DXVK currently.

**Comment by pchome** [comment]
I know nothing about macOS, but this issue can be similar to d3d10 linking issue for DXVK winelib build.
https://github.com/doitsujin/dxvk/pull/608/files

Try to replace `d3d11_dep` with `lib_d3d11` in `src/d3d10/meson.build`.

**Comment by Luke-Nukem** [comment]
@pchome that seems to have done the trick. Thanks! I'll do a PR upstream.

**Comment by nannanav** [comment]
@pchome How do I build the src/d3d10/meson.build file after making the above mentioned change?
